[[api-operation]]
= API Operation

[#192]
== {MUST} Publish OpenAPI Specification in Docker Artifacts

All service applications must publish OpenAPI Reference
Definitions of their external APIs. This is optional for internal APIs.

Publishing of the APIs is done via Docker image artifacts, following these rules:

If docker image provides one ore more APIs::
Copy the API Specifications in the `/zalando-apis` directory:

[source]
----
COPY my-api.yaml /zalando-apis/my-api.yaml
----

If docker image doesn't provide any APIs::
Put empty `no-apis` file into the `/zalando-apis` directory:

[source]
----
RUN mkdir /zalando-apis && touch /zalando-apis/no-apis
----

Please note that in the later case a shell has to be installed in the docker
container. Alternatively, you can create empty `no-apis` file locally and
make use of Docker `COPY` command in Dockerfile.

We prefer this publishing method over the legacy `.well-known` endpoint-based
discovery process. However, we support this way for backward compatibility
reasons.

We distinguish between internal and external APIs of an application
which is owned by a specific team and often implemented via small set of
services. An external API is used by clients outside the team - usually
another application owned by a different team or even an external
business partner user of our platform. An internal API is only used
within the application and only by the owning team, for instance, for
operational or implementation internal purposes.

Background: In our dynamic and complex service infrastructure, it is
important to provide API client developers a central place with online
access to the OpenAPI reference definitions of all running applications.
As a part of the Zalando infrastructure, the API Discovery process is used to
detect all API definitions. It scans all published Docker images and
correlates API-related information with running applications on AWS and
Kubernetes clusters. The findings are published in the API Portal - the
universal hub for all Zalando APIs.

[#193]
== {SHOULD} Monitor API Usage

Owners of APIs used in production should monitor API service to get
information about its using clients. This information, for instance, is
useful to identify potential review partner for API changes.

Hint: A preferred way of client detection implementation is by logging
of the client-id retrieved from the OAuth token.
